// This file is automatically generated from your CSS. Any edits will be overwritten.
export const backgroundGenerator: string;
export const shape: string;
export const triangle: string;
export const square: string;
export const circle: string;
